//Authentication Actions
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LOAD_APP_DATA = 'LOAD_APP_DATA';
export const LOAD_APP_DATA_ERROR = 'LOAD_APP_DATA_ERROR';
export const LOAD_APP_DATA_SUCCESS = 'LOAD_APP_DATA_SUCCESS';
export const INITIALIZE_USER = 'INITIALIZE_USER';

//Team actions
export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';
export const JOIN_TEAM = 'JOIN_TEAM';
export const JOIN_TEAM_SUCCESS = 'JOIN_TEAM_SUCCESS';
export const JOIN_TEAM_ERROR = 'JOIN_TEAM_ERROR';
export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_ERROR = 'FETCH_TEAMS_ERROR';
export const SELECT_TEAM = 'SELECT_TEAM';


//Chat Actions
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
export const CREATE_CHANNEL = 'CREATE_CHANNEL';
export const CREATE_CHANNEL_SUCCESS = 'CREATE_CHANNEL_SUCCESS';
export const CREATE_CHANNEL_ERROR = 'CREATE_CHANNEL_ERROR';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_ERROR = 'FETCH_CHANNELS_ERROR';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_ERROR = 'FETCH_MESSAGES_ERROR';
export const SEND_MESSAGE = 'SEND_MESSAGE';

//Workspace Actions
export const SELECT_WORKSPACE = 'SELECT_WORKSPACE';
export const CREATE_WORKSPACE = 'CREATE_WORKSPACE';
export const CREATE_WORKSPACE_SUCCESS = 'CREATE_WORKSPACE_SUCCESS';
export const CREATE_WORKSPACE_ERROR = 'CREATE_WORKSPACE_ERROR';
export const FETCH_WORKSPACES = 'FETCH_WORKSPACES';
export const FETCH_WORKSPACES_SUCCESS = 'FETCH_WORKSPACES_SUCCESS';
export const FETCH_WORKSPACES_ERROR = 'FETCH_WORKSPACES_ERROR';
export const JOIN_WORKSPACE = 'JOIN_WORKSPACE';
export const JOIN_WORKSPACE_SUCCESS = 'JOIN_WORKSPACE_SUCCESS';
export const JOIN_WORKSPACE_ERROR = 'JOIN_WORKSPACE_ERROR';
export const FETCH_WORKSPACE_USERS = 'FETCH_WORKSPACE_USERS';
export const FETCH_WORKSPACE_USERS_SUCCESS = 'FETCH_WORKSPACE_USERS_SUCCESS';
export const FETCH_WORKSPACE_USERS_ERROR = 'FETCH_WORKSPACE_USERS_ERROR';
